### PR TITLE
handle IDs that are numbers

### PR DESCRIPTION
**Pull request by gtchance**
If the ID value is a number, the casting to a String fails.

### CODE REVIEW

**Comment by lokakien** [comment]
From https://jsonapi.org/format/#document-resource-object-identification: 

>  The values of the id and type members MUST be strings.

**Comment by Truba** [comment]
Hi guys,

@lokakien is correct that id must be string. 
With that said, we are not against this PR, since adding some additional robustness is usually a good thing.
The only concern we have with this PR is possible drop in performance.

We are currently devising a way to benchmark this.

**Comment by marcusficner** [comment]
Have you also considered the case where id might be nil as stated in the exception here?

https://jsonapi.org/format/#document-resource-objects

**Comment by andrewtheis** [comment]
Any update on this @Truba ? We need this support as well.

**Pull request closed without merging**
